/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eclipse.screens;

import eclipse.Player_Party;
import eclipse.core;
import static eclipse.screens.Game_Screen.tabbedPane;
import java.io.File;
import java.io.IOException;
import javax.swing.JPanel;

/**
 *
 * @author Kealdor
 */
public class load_game_screen extends javax.swing.JPanel {

    /**
     * Creates new form load_game_screen
     */
    public load_game_screen() throws IOException {
        initComponents();
        core.log("load screen", "load screen rendered");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        load = new javax.swing.JButton();
        main_menu = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jFileChooser1.setApproveButtonText("");
        jFileChooser1.setApproveButtonToolTipText("");
        jFileChooser1.setControlButtonsAreShown(false);
        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\Users\\Kealdor"));
        jFileChooser1.setDialogTitle("Eclipse Evermore");
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.setName("load"); // NOI18N
        jFileChooser1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
        );

        load.setText("Load Character");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });

        main_menu.setText("Main Menu");
        main_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(load)
                .addGap(197, 197, 197)
                .addComponent(main_menu)
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 21, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 21, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(651, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(load)
                    .addComponent(main_menu))
                .addGap(14, 14, 14))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 44, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        File file = jFileChooser1.getSelectedFile();
        String name = file.getName();

        Player_Party party = null;

        try {
            core.log("load screen", "trying to generate loaded character");
            party = new Player_Party();
            party.Add_Member(name);
            core.log("load screen", "generated " + party.m1.name + " successfully");
        } catch (IOException ex) {
            try {
                core.log("load screen", "generated " + party.m1.name + " unsuccessfully");
            } catch (IOException ex1) {
            }
        }

        Game_Screen.tab = Game_Screen.tab--;
        tabbedPane.removeTabAt(1);
        Game_Screen.tab = Game_Screen.tab--;
        tabbedPane.removeTabAt(0);
        JPanel town = new Antioch_town();

        try {
            core.log("load screen", "sending " + party.m1.name + " to Antioch");
        } catch (IOException ex) {
            try {
                core.log("load screen", "unsuccessful in sending " + party.m1.name + " to Antioch");
            } catch (IOException ex1) {
            }
        }

        tabbedPane.add(town, 0);
        Game_Screen.tabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_loadActionPerformed

    private void main_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_menuActionPerformed
        String tab_name = null;
        int screen_number = 0;

        try {
            core.log("load screen", "looking for title screen to render it");
        } catch (IOException ex) {
        }
        while (!"Title".equals(tab_name)) {
            tab_name = tabbedPane.getTitleAt(screen_number);
            screen_number++;
        }

        if ("Title".equals(tab_name)) {
            int this_tab = tabbedPane.getSelectedIndex();
            title_screen.loadgame = false;
            try {
                core.log("load screen", "title screen found displaying it now");
            } catch (IOException ex) {
            }
            tabbedPane.setSelectedIndex(screen_number);
            Game_Screen.tab--;
            try {
                core.log("load screen", "closing load screen now");
            } catch (IOException ex) {
            }
            tabbedPane.removeTabAt(this_tab);
        }
    }//GEN-LAST:event_main_menuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton load;
    private javax.swing.JButton main_menu;
    // End of variables declaration//GEN-END:variables
}
